# Generated by Django 5.2.14 on 2026-06-01, then hand-edited to include data migration.

from django.db import migrations, models


def backfill_recording_type(apps, schema_editor):
    Recording = apps.get_model("journal", "Recording")
    for rec in Recording.objects.all():
        if rec.is_idea:
            rec.recording_type = "improvisation"
        elif rec.is_practice:
            rec.recording_type = "practice"
        else:
            rec.recording_type = "imported"
        rec.save(update_fields=["recording_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_comment_author_recording_owner_sharedrecording"),
    ]

    operations = [
        # 1. Add recording_type as nullable so existing rows don't break
        migrations.AddField(
            model_name="recording",
            name="recording_type",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("practice", "Practice"),
                    ("improvisation", "Improvisation"),
                    ("composition", "Composition"),
                    ("jam", "Jam Session"),
                    ("live", "Live Performance"),
                    ("cover", "Cover"),
                    ("demo", "Demo"),
                    ("imported", "Imported"),
                ],
                null=True,
            ),
        ),
        # 2. Backfill from old boolean fields
        migrations.RunPython(backfill_recording_type, migrations.RunPython.noop),
        # 3. Make non-nullable with default
        migrations.AlterField(
            model_name="recording",
            name="recording_type",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("practice", "Practice"),
                    ("improvisation", "Improvisation"),
                    ("composition", "Composition"),
                    ("jam", "Jam Session"),
                    ("live", "Live Performance"),
                    ("cover", "Cover"),
                    ("demo", "Demo"),
                    ("imported", "Imported"),
                ],
                default="practice",
            ),
        ),
        # 4. Remove old boolean fields
        migrations.RemoveField(model_name="recording", name="is_idea"),
        migrations.RemoveField(model_name="recording", name="is_practice"),
    ]
