# Generated by Django 5.2.14 on 2026-06-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='suno_raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='suno_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16, null=True),
        ),
    ]
