# Generated by Django 5.2.14 on 2026-06-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_suno_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='bpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='key',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
