# Generated by Django 5.2.14 on 2026-06-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_bpm_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='family',
            field=models.CharField(blank=True, choices=[('string', 'String'), ('keys', 'Keys'), ('synth', 'Synth'), ('wind', 'Wind'), ('brass', 'Brass'), ('percussion', 'Percussion'), ('voice', 'Voice'), ('electronic', 'Electronic'), ('field', 'Field Recording'), ('other', 'Other')], max_length=32),
        ),
    ]
