# Generated by Django 5.2.14 on 2026-06-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_instrument_family_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='peaks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
